on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cat
        run: |
          cat test.txt
