on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: WhoAmI
        run: whoami
      - name: Which group am I in
        run: groups
      - name: My frineds
        run: users
      - name: Where Am I
        run: pwd
      - name: What is my address
        run: curl ipinfo.io
      - name: Cat
        run: |
          cat test.txt
      - name: Touch
        run: touch grass.txt
      - name: Power touch
        run: sudo touch power.txt
      - name: ls
        run: ls -lha
      - name: Remove
        run: rm grass.txt
      - name: Power remove
        run: rm power.txt
      - name: The pass
        run: cat /etc/passwd
      - name: Cat visudo
        run: cat /etc/sudoers
