on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: WhoAmI
        run: whoami
      - name: Which group am I in
        run: groups
      - name: My frineds
        run: users
      - name: Where Am I
        run: pwd
      - name: What is my address
        run: curl ipinfo.io
      - name: Cat
        run: |
          cat test.txt
